# Generated by Django 3.0.4 on 2020-03-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200329_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpass',
            old_name='Cpass',
            new_name='cpass',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='Mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='uname',
            old_name='Uname',
            new_name='uname',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
